#!/usr/bin/env bash
#  a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
#shellcheck disable=SC2034
#shellcheck disable=SC2154
while IFS=: read -r username password userid group_id rest; do
  echo "The user $username is part of the $userid gang, lives in  and rides. $userid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
