#!/usr/bin/env bash
# this is a bash script about the if elif, else, and while loops
x=1
while [ $x -le 10 ]; do
	if [ $x -eq 4 ]; then
		echo "bad luck"
	elif [ $x -eq 8 ]; then
		echo "good luck"
	else 
		echo "Best School"
	fi	
	x=$((x+1))  
done

